### ISSUE TITLE
Bug: Left-invariant geodesics on SO(3) gives NaNs because of error in the optimization computing the log

### ISSUE THREAD

**Issue by psarahdactyl** [geomstats/geomstats#1825]
### Describe the bug

When making a left invariant metric on SO(3) and calling the geodesic function, I get NaNs (with autograd backend) and segfault (with pytorch background). In both backends, this bug doesn't happen everytime. After playing with the random seed I _think_ I found a version that always fails. Because of the segfault in pytorch, I did not get very far debugging it so all the information I have is done using the autograd backend.

### Steps/Code to Reproduce

In this code, I use the autograd background, make an instance of SO3, and make a left invariant metric with a specific metric matrix at identity.

I make a geodesic starting at the `initial_point` of the identity matrix, and going to the `end_point` of a generated rotation from an angle `theta`.

When I run this code, sometimes it will say `overflow encountered in matmul`

I've traced it back to calling the `scipy.optimize.minimize` function in [connection.py](https://github.com/geomstats/geomstats/blob/master/geomstats/geometry/connection.py#L180). Please see the stacktrace for more details.
In `connection.py` I've added this line fixing the random seed and changing the `disp` option to `True` to get more output.
This display option only works with the autograd backend; pytorch just segfaults.
```
  objective_with_grad = gs.autodiff.value_and_grad(objective, to_numpy=True)

  gs.random.seed(2)
  tangent_vec = gs.flatten(gs.random.rand(*max_shape))  #.numpy()
  print("connection::log - tangent_vec:", tangent_vec)
  print("connection::log - point:", point)
  print("connection::log - base_point:", base_point)
  print("connection::log minimize")
  res = minimize(
      objective_with_grad,
      tangent_vec,
      method="L-BFGS-B",
      jac=True,
      options={"disp": True, "maxiter": max_iter},
      tol=tol,
  )
```

main code:
```
import os
import numpy as np

os.environ["GEOMSTATS_BACKEND"] = "autograd"

import geomstats.backend as gs
gs.set_default_dtype("float64")
from geomstats.algebra_utils import from_vector_to_diagonal_matrix
from geomstats.geometry.invariant_metric import InvariantMetric
from geomstats.geometry.invariant_metric import BiInvariantMetric
from geomstats.geometry.special_orthogonal import SpecialOrthogonal

SO3 = SpecialOrthogonal(n=3, point_type="matrix")

initial_point = gs.eye(3)
print("initial point (identity)")
print(initial_point)

# testing a bunch of rotations
invariance = "left"
alpha = 100.
beta = 200.
metric_mat = from_vector_to_diagonal_matrix(gs.array([1, alpha, beta], dtype=gs.float64))
SO3_metric_from_z = InvariantMetric( 
    group=SO3, metric_mat_at_identity=metric_mat, left=invariance
)

theta = 1.5707963267948966

rot_vec = gs.array([theta, 0, 0], dtype=gs.float64)
print("rot_vec", rot_vec)
end_point = SO3.matrix_from_rotation_vector(rot_vec)
print("end_point", end_point)

print("new end point")
print(end_point)

geod = SO3_metric_from_z.geodesic(
  initial_point=initial_point, end_point=end_point
)
```

In my example with the random seed set, this code always crashes when:
`theta` is 1.5707963267948966
```
rot_vec [1.57079633 0.         0.        ]
end_point [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.11022302e-16 -1.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  1.11022302e-16]]
```
and happens in the log minimize at iterate 1:
```
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            9     M =           10
 This problem is unconstrained.

At X0         0 variables are exactly at the bounds

At iterate    0    f=  6.85249D+00    |proj g|=  5.95710D+00

At iterate    1    f=  3.12405D+00    |proj g|=  8.12174D+00
```

### Expected Behaviour

I expect the minimization to happen without crashing or overflowing.

### Actual Behaviour

The actual behavior I get is NaNs, which come from an overflow in matrix multiplication with really big numbers.
The `point` in [lie_group.py](https://github.com/geomstats/geomstats/blob/master/geomstats/geometry/lie_group.py#L111) is sometimes way too big. Based on the rotation matrices I put into the geodesic function, I have no idea how they get this big?

The output from my code is:
```
theta 2 : 1.5707963267948966
rot_vec [1.57079633 0.         0.        ]
end_point [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.11022302e-16 -1.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  1.11022302e-16]]
new end point
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.11022302e-16 -1.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  1.11022302e-16]]
in end_point is not None
connection::log first line
connection::log - tangent_vec: [0.4359949  0.02592623 0.54966248 0.43532239 0.4203678  0.33033482
 0.20464863 0.61927097 0.29965467]
connection::log - point: [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.11022302e-16 -1.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  1.11022302e-16]]
connection::log - base_point: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
connection::log minimize
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =            9     M =           10
 This problem is unconstrained.

At X0         0 variables are exactly at the bounds

At iterate    0    f=  6.85249D+00    |proj g|=  5.95710D+00

At iterate    1    f=  3.12405D+00    |proj g|=  8.12174D+00
point in lie group Autograd ArrayBox with value [[-4.02833799e+12 -7.14101588e+11  2.00137685e+13]
 [ 1.89508196e+13 -6.10756033e+13 -2.92547852e+13]
 [ 5.94233371e+12  2.89180626e+13 -5.75876483e+13]]
max in matmul Autograd ArrayBox with value 28918062589218.758
max in matmul Autograd ArrayBox with value 5485289281580040.0
max in matmul Autograd ArrayBox with value 5485289281580040.0
max in matmul Autograd ArrayBox with value 5485289281580040.0
max in matmul Autograd ArrayBox with value 5485289281580040.0
max in matmul Autograd ArrayBox with value 5485289281580040.0
max in matmul Autograd ArrayBox with value 5485289281580040.0
max in matmul Autograd ArrayBox with value 5485289281580040.0
point in lie group Autograd ArrayBox with value [[-1.14404121e+26 -1.22561332e+27 -6.67575866e+25]
 [ 2.56991456e+26  1.81039479e+27 -3.61310992e+27]
 [ 2.90368856e+26  3.51841907e+27  1.79676258e+27]]
max in matmul Autograd ArrayBox with value 3.5184190658584877e+27
max in matmul Autograd ArrayBox with value 7.50111288792896e+28
max in matmul Autograd ArrayBox with value 7.50111288792896e+28
max in matmul Autograd ArrayBox with value 7.50111288792896e+28
max in matmul Autograd ArrayBox with value 7.50111288792896e+28
max in matmul Autograd ArrayBox with value 7.50111288792896e+28
max in matmul Autograd ArrayBox with value 7.50111288792896e+28
max in matmul Autograd ArrayBox with value 7.50111288792896e+28
point in lie group Autograd ArrayBox with value [[-6.04707912e+53 -1.07196288e+53  3.00433682e+54]
 [ 2.84477384e+54 -9.16827252e+54 -4.39153818e+54]
 [ 8.92024508e+53  4.34099157e+54 -8.64468341e+54]]
max in matmul Autograd ArrayBox with value 4.3409915671647695e+54
max in matmul Autograd ArrayBox with value 8.23415968526079e+56
max in matmul Autograd ArrayBox with value 8.23415968526079e+56
max in matmul Autograd ArrayBox with value 8.23415968526079e+56
max in matmul Autograd ArrayBox with value 8.23415968526079e+56
max in matmul Autograd ArrayBox with value 8.23415968526079e+56
max in matmul Autograd ArrayBox with value 8.23415968526079e+56
max in matmul Autograd ArrayBox with value 8.23415968526079e+56
point in lie group Autograd ArrayBox with value [[-7.73396889e+108 -8.28541419e+109 -4.51295892e+108]
 [ 1.73731847e+109  1.22386649e+110 -2.44254136e+110]
 [ 1.96295700e+109  2.37852827e+110  1.21465081e+110]]
max in matmul Autograd ArrayBox with value 2.3785282709194803e+110
max in matmul Autograd ArrayBox with value 5.070916435289435e+111
max in matmul Autograd ArrayBox with value 5.070916435289435e+111
max in matmul Autograd ArrayBox with value 5.070916435289435e+111
max in matmul Autograd ArrayBox with value 5.070916435289435e+111
max in matmul Autograd ArrayBox with value 5.070916435289435e+111
max in matmul Autograd ArrayBox with value 5.070916435289435e+111
max in matmul Autograd ArrayBox with value 5.070916435289435e+111
point in lie group Autograd ArrayBox with value [[-5.52709783e+219 -9.79786041e+218  2.74599739e+220]
 [ 2.60015505e+220 -8.37990344e+220 -4.01391493e+220]
 [ 8.15320358e+219  3.96771476e+220 -7.90133714e+220]]
max in matmul Autograd ArrayBox with value 3.9677147552559575e+220
max in matmul Autograd ArrayBox with value 7.526113878558229e+222
/Users/sak/opt/anaconda3/envs/supersampling/lib/python3.10/site-packages/autograd/tracer.py:48: RuntimeWarning: overflow encountered in matmul
  return f_raw(*args, **kwargs)
max in matmul Autograd ArrayBox with value 7.526113878558229e+222
max in matmul Autograd ArrayBox with value 7.526113878558229e+222
max in matmul Autograd ArrayBox with value 7.526113878558229e+222
max in matmul Autograd ArrayBox with value 7.526113878558229e+222
max in matmul Autograd ArrayBox with value 7.526113878558229e+222
max in matmul Autograd ArrayBox with value 7.526113878558229e+222
point in lie group Autograd ArrayBox with value [[ inf -inf -inf]
 [ inf  inf  inf]
 [-inf  inf  inf]]
max in matmul Autograd ArrayBox with value inf
```

The line numbers here may not be exactly right since I've added print statements and raise ValueErrors, but here is the stacktrace.

```
Traceback (most recent call last):
  File "/Users/sak/Documents/Documents-sarahs-macbook/supersampling/supersampling/reproduce_nans.py", line 87, in <module>
    geod = SO3_metric_from_z.geodesic(
  File "/Users/sak/opt/anaconda3/envs/supersampling/lib/python3.10/site-packages/geomstats/geometry/connection.py", line 678, in geodesic
    shooting_tangent_vec = self.log(point=end_point, base_point=initial_point)
  File "/Users/sak/opt/anaconda3/envs/supersampling/lib/python3.10/site-packages/geomstats/geometry/invariant_metric.py", line 686, in log
    super().log(
  File "/Users/sak/opt/anaconda3/envs/supersampling/lib/python3.10/site-packages/geomstats/geometry/connection.py", line 185, in log
    res = minimize(
  File "/Users/sak/.local/lib/python3.10/site-packages/scipy/optimize/_minimize.py", line 699, in minimize
    res = _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "/Users/sak/.local/lib/python3.10/site-packages/scipy/optimize/_lbfgsb_py.py", line 362, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/Users/sak/.local/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 285, in fun_and_grad
    self._update_fun()
  File "/Users/sak/.local/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 251, in _update_fun
    self._update_fun_impl()
  File "/Users/sak/.local/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 155, in update_fun
    self.f = fun_wrapped(self.x)
  File "/Users/sak/.local/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 137, in fun_wrapped
    fx = fun(np.copy(x), *args)
  File "/Users/sak/.local/lib/python3.10/site-packages/scipy/optimize/_optimize.py", line 76, in __call__
    self._compute_if_needed(x, *args)
  File "/Users/sak/.local/lib/python3.10/site-packages/scipy/optimize/_optimize.py", line 70, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/Users/sak/opt/anaconda3/envs/supersampling/lib/python3.10/site-packages/geomstats/_backend/autograd/autodiff.py", line 142, in func_with_grad
    value_i, grad_i = _value_and_grad(func_of_ith)(*new_args)
  File "/Users/sak/opt/anaconda3/envs/supersampling/lib/python3.10/site-packages/autograd/wrap_util.py", line 20, in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
  File "/Users/sak/opt/anaconda3/envs/supersampling/lib/python3.10/site-packages/autograd/differential_operators.py", line 138, in value_and_grad
    vjp, ans = _make_vjp(fun, x)
  File "/Users/sak/opt/anaconda3/envs/supersampling/lib/python3.10/site-packages/autograd/core.py", line 10, in make_vjp
    end_value, end_node =  trace(start_node, fun, x)
  File "/Users/sak/opt/anaconda3/envs/supersampling/lib/python3.10/site-packages/autograd/tracer.py", line 10, in trace
    end_box = fun(start_box)
  File "/Users/sak/opt/anaconda3/envs/supersampling/lib/python3.10/site-packages/autograd/wrap_util.py", line 15, in unary_f
    return fun(*subargs, **kwargs)
  File "/Users/sak/opt/anaconda3/envs/supersampling/lib/python3.10/site-packages/geomstats/_backend/autograd/autodiff.py", line 139, in func_of_ith
    return func(*reorg_args)
  File "/Users/sak/opt/anaconda3/envs/supersampling/lib/python3.10/site-packages/geomstats/geometry/connection.py", line 174, in objective
    delta = self.exp(velocity, base_point, n_steps, step) - point
  File "/Users/sak/opt/anaconda3/envs/supersampling/lib/python3.10/site-packages/geomstats/geometry/invariant_metric.py", line 615, in exp
    flow = integrate(lie_acceleration, initial_state, n_steps=n_steps, step=step)
  File "/Users/sak/opt/anaconda3/envs/supersampling/lib/python3.10/site-packages/geomstats/integrator.py", line 209, in integrate
    current_state = step_function(
  File "/Users/sak/opt/anaconda3/envs/supersampling/lib/python3.10/site-packages/geomstats/integrator.py", line 163, in rk4_step
    k1 = force(state, time)
  File "/Users/sak/opt/anaconda3/envs/supersampling/lib/python3.10/site-packages/geomstats/geometry/invariant_metric.py", line 594, in lie_acceleration
    velocity = self.group.tangent_translation_map(point, left=self.left)(vector)
  File "/Users/sak/opt/anaconda3/envs/supersampling/lib/python3.10/site-packages/geomstats/geometry/lie_group.py", line 113, in <lambda>
    return lambda tangent_vec: self.compose(point, tangent_vec)
  File "/Users/sak/opt/anaconda3/envs/supersampling/lib/python3.10/site-packages/geomstats/geometry/lie_group.py", line 60, in compose
    return Matrices.mul(point_a, point_b)
  File "/Users/sak/opt/anaconda3/envs/supersampling/lib/python3.10/site-packages/geomstats/geometry/matrices.py", line 74, in mul
    return reduce(gs.matmul, args)
  File "/Users/sak/opt/anaconda3/envs/supersampling/lib/python3.10/site-packages/geomstats/_backend/autograd/__init__.py", line 504, in matmul
    raise ValueError("nan")
ValueError: nan
```

### Your environment

```shell
I am using MacOS.
Processor 2.3 GHz Quad-Core Intel Core i5
Memory 16 GB 2133 MHz LPDDR3
Graphics Intel Iris Plus Graphics 655 1536 MB

I am using the latest geomstats version from github:

| 💯 => python
Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:27:35) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> scipy.__version__
'1.9.2'
>>> import numpy
>>> numpy.__version__
'1.23.5'
>>> import geomstats
>>> geomstats.__version__
'2.5.0'
>>> import sys
>>> sys.version
'3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:27:35) [Clang 14.0.6 ]'
>>>
```

**Comment by luisfpereira** [comment]
Thanks for the nice description of the error @psarahdactyl! It really helped figuring out what's going on.

The issue here is the numerical parameters to solve the `exp` integration problem. I guess for some input point combinations the problem becomes harder and the default numerical parameters are not properly set to solve it accurately. This means that for the geodesic it will simply "explode" and that's the reason we get the NaNs.

We are currently refactoring the way we solve numerical problems within `geomstats`, and I think the new strategy will simplify the handling of numerical parameters. For now, I recommend you to do something like:

```python
initial_tangent_vec = metric.log(
    end_point, initial_point, max_iter=100,
)

geod = metric.geodesic(
  initial_point=initial_point, initial_tangent_vec=initial_tangent_vec, max_iter=100,
)
```

The reason to get the `initial_tangent_vec` outside is that (currently) `geodesic` transforms the `end_point` into an initial tangent vector, but we cannot control the input parameters of this operation (this is one of the reasons we are rethinking the numerical solvers).

Notice that increasing the number of iterations will make the computations more expensive.

Let me know if this works.

P.S. with the last updates in `InvariantMetric`, part of the code above should be adapted to something like:

```python
left = True

SO3_metric_from_z = InvariantMetric( 
    group=SO3, metric_mat_at_identity=metric_mat, left=left
)
````

i.e. we changed `invariance` to be a boolean described by `left`, so we can avoid typos due to string use and simplify the check of the input arguments.

**Comment by ninamiolane** [comment]
Thanks @psarahdactyl for the well-written issue, very helpful indeed.

I was able to reproduce that error. @luisfpereira unfortunately the error does not go away with the computation of the initial tangent vector beforehand.

**Comment by ninamiolane** [comment]
@psarahdactyl @luisfpereira replacing Luis' code snippet with:
```
initial_tangent_vec = SO3_metric_from_z.log(
    end_point, initial_point, max_iter=30, tol=1e-8, n_steps=30,
)
```
fixed it on my side. The parameter `n_steps=30` helped, in particular setting it to 25 still creates NaNs.

**Comment by luisfpereira** [comment]
@psarahdactyl, I think in the new version of geomstats this works perfectly well. We also have more control over the numerical parameters for the `exp` and `log` in case we need. You need to change your code for:

```python
SO3 = SpecialOrthogonal(n=3, point_type="matrix", equip=False)

left = True
alpha = 100.
beta = 200.

metric_mat = from_vector_to_diagonal_matrix(gs.array([1, alpha, beta], dtype=gs.float64))
SO3.equip_with_metric(InvariantMetric, metric_mat_at_identity=metric_mat, left=left)
```


I'm closing the issue. Please reopen it if you still have problems.

**Comment by psarahdactyl** [comment]
With lower alpha and beta values (0.0001 < a,b < 30), it _usually_ works fine. Sometimes I need to compute the exp with a higher number of integration steps. but even then it still fails sometimes -- with matmul overflow which leads to NaNs -- for reasons I don't understand.
